"""
Tally Prime integration via Tally Developer Gateway (local HTTP server).

Tally must be running on the client's machine with TDL Gateway enabled.
The Gateway exposes an HTTP endpoint (default http://localhost:9000) that
accepts Tally XML Import Data payloads and returns an XML response.

How to enable in Tally Prime:
  Gateway > Settings > Enable TDL Gateway Server (port 9000 by default)
  Or launch Tally with: tally.exe /GATEWAYON

XML format used: standard Tally Import Data (IMPORTDATA / REQUESTDESC=Vouchers)
— the same format already generated by the frontend file-export in erp/page.tsx.
"""
import httpx
import xml.etree.ElementTree as ET
from datetime import datetime
from typing import Any


def _tally_date(iso_date: str) -> str:
    """Convert YYYY-MM-DD to Tally's DD/MM/YYYY."""
    if not iso_date or len(iso_date) < 10:
        return iso_date
    y, m, d = iso_date[:10].split("-")
    return f"{d}/{m}/{y}"


def _f(v: Any) -> float:
    try:
        return float(v or 0)
    except (TypeError, ValueError):
        return 0.0


def build_initial_recognition_xml(
    lease_id: str,
    rou: float,
    liability: float,
    date_str: str,
    account_mapping: dict,
    company: str = "",
) -> str:
    """Build Tally Import Data XML for the initial recognition journal entry."""
    tally_dt = _tally_date(date_str)
    rou_ledger = account_mapping.get("rou_asset", "Right-of-Use Asset")
    ll_ledger = account_mapping.get("lease_liability", "Lease Liability")

    voucher = f"""<VOUCHER VCHTYPE="Journal" ACTION="Create" OBJVIEW="Accounting Voucher View">
            <DATE>{tally_dt}</DATE>
            <NARRATION>IFRS 16 Initial Recognition - {lease_id}</NARRATION>
            <ALLLEDGERENTRIES.LIST>
              <LEDGERNAME>{rou_ledger}</LEDGERNAME>
              <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
              <AMOUNT>{rou:.2f}</AMOUNT>
            </ALLLEDGERENTRIES.LIST>
            <ALLLEDGERENTRIES.LIST>
              <LEDGERNAME>{ll_ledger}</LEDGERNAME>
              <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
              <AMOUNT>-{liability:.2f}</AMOUNT>
            </ALLLEDGERENTRIES.LIST>
          </VOUCHER>"""

    return _wrap_vouchers(company, [voucher])


def build_monthly_xml(
    lease_id: str,
    period: str,
    date_str: str,
    interest: float,
    payment: float,
    depreciation: float,
    account_mapping: dict,
    company: str = "",
) -> str:
    """
    Build Tally Import Data XML for the monthly IFRS 16 journal entries.

    Three balanced vouchers (mirrors map_monthly_entry logic):
      1. Interest accrual: Dr Interest Expense / Cr Lease Liability
      2. Lease payment:    Dr Lease Liability / Cr Cash  (full payment)
      3. Depreciation:     Dr Depreciation Expense / Cr Accumulated Depreciation
    """
    tally_dt = _tally_date(date_str)
    ll = account_mapping.get("lease_liability", "Lease Liability")
    int_exp = account_mapping.get("interest_expense", "Finance Cost")
    dep_exp = account_mapping.get("depreciation", "Depreciation Expense")
    acc_dep = account_mapping.get("acc_dep_rou", "Accumulated Depreciation - ROU")
    cash = account_mapping.get("cash", "Bank/Cash")

    vouchers = []

    # Voucher 1 — interest accrual
    if interest > 0:
        vouchers.append(f"""<VOUCHER VCHTYPE="Journal" ACTION="Create" OBJVIEW="Accounting Voucher View">
            <DATE>{tally_dt}</DATE>
            <NARRATION>IFRS 16 Interest Accrual - {lease_id} ({period})</NARRATION>
            <ALLLEDGERENTRIES.LIST>
              <LEDGERNAME>{int_exp}</LEDGERNAME>
              <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
              <AMOUNT>{interest:.2f}</AMOUNT>
            </ALLLEDGERENTRIES.LIST>
            <ALLLEDGERENTRIES.LIST>
              <LEDGERNAME>{ll}</LEDGERNAME>
              <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
              <AMOUNT>-{interest:.2f}</AMOUNT>
            </ALLLEDGERENTRIES.LIST>
          </VOUCHER>""")

    # Voucher 2 — lease payment (full payment to LL, matches entry 2 in mapper)
    if payment > 0:
        vouchers.append(f"""<VOUCHER VCHTYPE="Journal" ACTION="Create" OBJVIEW="Accounting Voucher View">
            <DATE>{tally_dt}</DATE>
            <NARRATION>IFRS 16 Lease Payment - {lease_id} ({period})</NARRATION>
            <ALLLEDGERENTRIES.LIST>
              <LEDGERNAME>{ll}</LEDGERNAME>
              <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
              <AMOUNT>{payment:.2f}</AMOUNT>
            </ALLLEDGERENTRIES.LIST>
            <ALLLEDGERENTRIES.LIST>
              <LEDGERNAME>{cash}</LEDGERNAME>
              <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
              <AMOUNT>-{payment:.2f}</AMOUNT>
            </ALLLEDGERENTRIES.LIST>
          </VOUCHER>""")

    # Voucher 3 — depreciation
    if depreciation > 0:
        vouchers.append(f"""<VOUCHER VCHTYPE="Journal" ACTION="Create" OBJVIEW="Accounting Voucher View">
            <DATE>{tally_dt}</DATE>
            <NARRATION>IFRS 16 ROU Depreciation - {lease_id} ({period})</NARRATION>
            <ALLLEDGERENTRIES.LIST>
              <LEDGERNAME>{dep_exp}</LEDGERNAME>
              <ISDEEMEDPOSITIVE>Yes</ISDEEMEDPOSITIVE>
              <AMOUNT>{depreciation:.2f}</AMOUNT>
            </ALLLEDGERENTRIES.LIST>
            <ALLLEDGERENTRIES.LIST>
              <LEDGERNAME>{acc_dep}</LEDGERNAME>
              <ISDEEMEDPOSITIVE>No</ISDEEMEDPOSITIVE>
              <AMOUNT>-{depreciation:.2f}</AMOUNT>
            </ALLLEDGERENTRIES.LIST>
          </VOUCHER>""")

    return _wrap_vouchers(company, vouchers)


def _wrap_vouchers(company: str, vouchers: list[str]) -> str:
    """Wrap voucher XML fragments in the Tally Import Data envelope."""
    company_tag = f"<SVCURRENTCOMPANY>{company}</SVCURRENTCOMPANY>" if company else ""
    messages = "\n".join(
        f"          <TALLYMESSAGE>\n            {v}\n          </TALLYMESSAGE>"
        for v in vouchers
    )
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<ENVELOPE>
  <HEADER>
    <TALLYREQUEST>Import Data</TALLYREQUEST>
  </HEADER>
  <BODY>
    <IMPORTDATA>
      <REQUESTDESC>
        <REPORTNAME>Vouchers</REPORTNAME>
        {company_tag}
      </REQUESTDESC>
      <REQUESTDATA>
{messages}
      </REQUESTDATA>
    </IMPORTDATA>
  </BODY>
</ENVELOPE>"""


def _parse_tally_response(xml_text: str) -> dict:
    """
    Parse Tally Gateway XML response. Returns {success, created, altered, errors, raw}.
    Tally responds with RESPONSE/IMPORTRESULT containing CREATED, ALTERED, ERRORS counts.
    """
    try:
        root = ET.fromstring(xml_text)
        # Tally 9.x / Prime response shape
        result_node = root.find(".//IMPORTRESULT")
        if result_node is None:
            result_node = root.find(".//RESPONSE")
        if result_node is None:
            # Some versions return STATUS/DESCRIPTION
            status = root.findtext(".//STATUS") or ""
            desc = root.findtext(".//DESCRIPTION") or xml_text[:300]
            success = status.strip() == "1" or "success" in desc.lower()
            return {"success": success, "created": 0, "altered": 0, "errors": 0, "raw": xml_text[:500]}

        created = int(result_node.findtext("CREATED") or "0")
        altered = int(result_node.findtext("ALTERED") or "0")
        errors = int(result_node.findtext("ERRORS") or "0")
        return {
            "success": errors == 0 and (created + altered) > 0,
            "created": created,
            "altered": altered,
            "errors": errors,
            "raw": xml_text[:500],
        }
    except ET.ParseError:
        # Some Tally versions return plain-text success messages
        success = "success" in xml_text.lower() or "voucher" in xml_text.lower()
        return {"success": success, "created": 0, "altered": 0, "errors": 0, "raw": xml_text[:500]}


class TallyPrimeClient:
    """
    Tally Prime integration via Tally Developer Gateway (local HTTP server).

    Connects to Tally running on the client's machine with TDL Gateway enabled.
    Gateway URL is typically http://localhost:9000 but is configurable.
    """

    def __init__(self, gateway_url: str = "http://localhost:9000", company: str = ""):
        self.gateway_url = gateway_url.rstrip("/")
        self.company = company

    async def ping(self) -> dict:
        """Check that Tally Gateway is reachable. Returns {reachable, version_raw}."""
        ping_xml = """<?xml version="1.0" encoding="UTF-8"?>
<ENVELOPE>
  <HEADER><TALLYREQUEST>Export Data</TALLYREQUEST></HEADER>
  <BODY>
    <EXPORTDATA>
      <REQUESTDESC><REPORTNAME>List of Companies</REPORTNAME></REQUESTDESC>
    </EXPORTDATA>
  </BODY>
</ENVELOPE>"""
        try:
            async with httpx.AsyncClient() as client:
                resp = await client.post(
                    self.gateway_url,
                    content=ping_xml,
                    headers={"Content-Type": "application/xml"},
                    timeout=10,
                )
            return {"reachable": True, "version_raw": resp.text[:200]}
        except Exception as exc:
            return {"reachable": False, "error": str(exc)}

    async def push_voucher(self, tally_xml: str) -> dict:
        """
        POST Tally Import Data XML to the Gateway and return a parsed result dict.
        Raises httpx.HTTPError on network failures; returns result dict otherwise.
        Result: {success, created, altered, errors, raw}
        """
        async with httpx.AsyncClient() as client:
            resp = await client.post(
                self.gateway_url,
                content=tally_xml.encode("utf-8"),
                headers={"Content-Type": "application/xml"},
                timeout=30,
            )
        return _parse_tally_response(resp.text)

    async def push_initial_recognition(
        self, lease_id: str, rou: float, liability: float,
        date_str: str, account_mapping: dict
    ) -> dict:
        xml = build_initial_recognition_xml(
            lease_id, rou, liability, date_str, account_mapping, self.company
        )
        return await self.push_voucher(xml)

    async def push_monthly_entry(
        self, lease_id: str, period: str, date_str: str,
        interest: float, payment: float, depreciation: float,
        account_mapping: dict
    ) -> dict:
        xml = build_monthly_xml(
            lease_id, period, date_str, interest, payment, depreciation,
            account_mapping, self.company
        )
        return await self.push_voucher(xml)
